-- Event seed data — mirrors lib/data.ts

insert into public.events (id, title, subtitle, date, time, city, venue, address, guests, status, featured, description, image_url, long_description, speakers, agenda) values
  ('ev-may26-zh', 'SportNexus Lunch Zürich', 'Talk mit Roger Federer Foundation', '2026-05-12', '11:30 – 14:00', 'Zürich', 'Widder Hotel', 'Rennweg 7, 8001 Zürich', 70, 'upcoming', true,
    'Über Philanthropie im Sport — wie aus einer Karriere eine Bewegung wird. Moderation: Andrea Vetsch.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/699dac7587d29f125390fc74_NEXUS_ZUERICH_IBIY_36.jpg',
    'Philanthropie als Fortsetzung der sportlichen Karriere. Wie Stiftungsarbeit professionell aufgestellt wird, welche Hebel wirklich zählen, und was Unternehmer davon lernen können — im persönlichen Gespräch mit der Roger Federer Foundation.',
    '[{"name":"Roger Federer Foundation","role":"Keynote"},{"name":"Andrea Vetsch","role":"Moderation"}]'::jsonb,
    '[{"t":"11:30","l":"Empfang & Apéro"},{"t":"12:15","l":"Talk & Q&A"},{"t":"13:00","l":"Lunch & Networking"},{"t":"14:00","l":"Abschluss"}]'::jsonb),
  ('ev-jun26-bs', 'SportNexus Lunch Basel', 'Andy Egli: Trainer-Leben', '2026-06-04', '11:30 – 14:00', 'Basel', 'Atlantis Basel', 'Klosterberg 13, 4051 Basel', 65, 'upcoming', false,
    'Vom Nati-Spieler zum Trainer — was Führung im Fussball mit Führung im Unternehmen zu tun hat.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/699da8d8b55537cfb726d358_A7401670.jpg',
    'Vom Stammspieler der Nati zur Seitenlinie — Andy Egli über die Psychologie des Gewinnens, den Umgang mit Niederlagen, und warum Führungskräfte im Unternehmen oft die gleichen Themen haben wie Trainer auf dem Platz.',
    '[{"name":"Andy Egli","role":"Ex-Nati-Spieler & Trainer"}]'::jsonb,
    '[{"t":"11:30","l":"Empfang"},{"t":"12:15","l":"Talk"},{"t":"13:00","l":"Lunch"},{"t":"14:00","l":"Ende"}]'::jsonb),
  ('ev-sep26-zg', 'SportNexus Dinner Zug', 'Unternehmer-Dinner', '2026-09-18', '18:30 – 23:00', 'Zug', 'Parkhotel Zug', 'Industriestrasse 14, 6300 Zug', 40, 'upcoming', false,
    'Exklusives Abend-Format: 40 Unternehmer, ein langer Tisch, vier Gänge.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/69b148832365b2d645660b2a_SportNexus-Ma%CC%88rz26-KMEDIA-DSC02089-A.jpg',
    'Ein Abend, ein langer Tisch, 40 Unternehmer. Wir öffnen den Raum für echte Gespräche — ohne Agenda-Druck, ohne Bühne. Nur zwei kuratierte Impulse zwischen den Gängen.',
    '[{"name":"Thema","role":"Nachfolge im Familienunternehmen"}]'::jsonb,
    '[{"t":"18:30","l":"Apéro"},{"t":"19:30","l":"Dinner & Gespräche"},{"t":"22:00","l":"Digestif"}]'::jsonb),
  ('ev-nov26-zh', 'SportNexus Year End Zürich', 'Jahres-Get-Together', '2026-11-26', '17:00 – 22:00', 'Zürich', 'Dolder Grand', 'Kurhausstrasse 65, 8032 Zürich', 120, 'upcoming', false,
    'Das Year-End der Community. Talks, Aperitif, Dinner — und die Vorschau auf 2027.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/699dae3f5dc68642ba59b47b_BF105291.jpg',
    'Das Year-End-Event bringt die gesamte Community unter einem Dach zusammen. Rückblick auf das Jahr, Ausblick auf 2027, und ein Abend, der in Erinnerung bleibt. Dresscode: Business Smart.',
    '[{"name":"SportNexus Gründerteam","role":"Jahresrückblick"},{"name":"Gastredner","role":"TBA"}]'::jsonb,
    '[{"t":"17:00","l":"Check-in & Apéro"},{"t":"18:00","l":"Jahresrückblick"},{"t":"18:45","l":"Keynote"},{"t":"19:30","l":"Dinner"},{"t":"22:00","l":"Ausklang"}]'::jsonb),
  ('ev-mar26-zh', 'SportNexus Lunch Zürich', 'Andy Schmid & Pascal Jenny', '2026-03-03', '11:30 – 14:00', 'Zürich', 'Restaurant Metropol', 'Fraumünsterstrasse 12, 8001 Zürich', 70, 'past', false,
    'Pokal, National-Trainer und 70 Teilnehmende. Die zwei Aushängeschilder des Schweizer Handballs im Talk.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/69b148832365b2d645660b2a_SportNexus-Ma%CC%88rz26-KMEDIA-DSC02089-A.jpg',
    'Eine leistungsorientierte Wohlfühloase, grosse Ziele und ein Team auf dem Weg zur Weltspitze. 70 Teilnehmende, Pokal auf dem Tisch.',
    '[{"name":"Andy Schmid","role":"Handball-Legende"},{"name":"Pascal Jenny","role":"Nationaltrainer"}]'::jsonb,
    '[]'::jsonb),
  ('ev-jan26-zh', 'SportNexus Lunch Zürich', 'Daniel & Jonas Kalt', '2026-01-22', '11:30 – 14:00', 'Zürich', 'Baur au Lac', 'Talstrasse 1, 8001 Zürich', 68, 'past', false,
    'Vater und Sohn über Wahrscheinlichkeiten — im Sport und an den Finanzmärkten.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/699dae3f5dc68642ba59b47b_BF105291.jpg',
    'Daniel und Sohn Jonas über Wahrscheinlichkeiten — im Sport und an den Finanzmärkten. Ein Dialog zwischen zwei Generationen und zwei Welten, die näher beieinander liegen als man denkt.',
    '[{"name":"Daniel Kalt","role":"UBS Chief Economist"},{"name":"Jonas Kalt","role":"Profi-Sportler"}]'::jsonb,
    '[]'::jsonb);
