-- Event seed data — mirrors lib/data.ts
-- Upcoming events synced from https://events.guestoo.de/sportnexus

insert into public.events (id, title, subtitle, date, time, city, venue, address, guests, status, featured, description, image_url, long_description, speakers, agenda) values
  ('ev-apr26-zh-coffee', 'SportNexus Coffee Connect Zürich', 'Netzwerken bei einer Tasse Kaffee', '2026-04-28', '07:30 – 09:00', 'Zürich', 'Alferano Store', 'Zürich', 7, 'upcoming', true,
    'Entspanntes Morgen-Networking bei einer Tasse Kaffee.',
    'https://events.guestoo.de/proxy/api/asset/14ffd81f-8133-45e0-b0fa-cb9bf669783a.png?x=1775588079962',
    'Starte deinen Tag mit Members aus dem SportNexus-Kreis. Kein Programm, keine Agenda — Kaffee, ein paar bekannte und ein paar neue Gesichter.',
    '[]'::jsonb,
    '[{"t":"07:30","l":"Kaffee & Ankommen"},{"t":"09:00","l":"Abschluss"}]'::jsonb),
  ('ev-apr26-bs-coffee', 'SportNexus Coffee Connect Basel', 'Netzwerken bei einer Tasse Kaffee', '2026-04-28', '07:30 – 09:00', 'Basel', 'Kaffeemacher Café Bahnhof SBB', 'Bahnhof SBB, Basel', 28, 'upcoming', false,
    'Entspanntes Morgen-Networking bei einer Tasse Kaffee.',
    'https://events.guestoo.de/proxy/api/asset/10cef4e0-c60f-4f77-8417-4d6ab098a7cf.png?x=1775586614775',
    'Basler Ausgabe des Coffee Connect — direkt am Bahnhof SBB. Ideal vor dem Arbeitstag, kurz und unkompliziert.',
    '[]'::jsonb,
    '[{"t":"07:30","l":"Kaffee & Ankommen"},{"t":"09:00","l":"Abschluss"}]'::jsonb),
  ('ev-may26-zh-lunch', '9. SportNexus-Lunch Zürich', 'Kerstin Kündig & Felix Rübel', '2026-05-07', '11:30 – 14:00', 'Zürich', 'Santa Lucia Teatro', 'Zürich', 35, 'upcoming', false,
    'Lunch-Talk mit Kerstin Kündig und Felix Rübel im Santa Lucia Teatro.',
    'https://events.guestoo.de/proxy/api/asset/69e8738b-85ca-4825-b3cf-b46acb6cca8e.jpg?x=1770121460019',
    'Die neunte Ausgabe des SportNexus-Lunches in Zürich. Kerstin Kündig und Felix Rübel im Gespräch — Einblicke aus Sport und Unternehmertum in kurzen Impulsen, danach Lunch und Networking am Tisch.',
    '[{"name":"Kerstin Kündig","role":"Gast"},{"name":"Felix Rübel","role":"Gast"}]'::jsonb,
    '[{"t":"11:30","l":"Empfang"},{"t":"12:15","l":"Talk"},{"t":"13:00","l":"Lunch"},{"t":"14:00","l":"Abschluss"}]'::jsonb),
  ('ev-may26-padel', '1. Padel-Memberturnier', 'SportNexus x Padelwerk', '2026-05-27', '16:30 – 23:30', 'Münchenstein', 'Padelwerk Münchenstein', 'Münchenstein', 18, 'upcoming', false,
    'Erstes Memberturnier auf dem Court — Padel, Apéro und Abendessen.',
    'https://events.guestoo.de/proxy/api/asset/de52057d-671a-4de9-9ec2-5cd6f64446c1.png?x=1775588852493',
    'Die erste Padel-Ausgabe für Members. In Kooperation mit Padelwerk Münchenstein: lockeres Turnier, Apéro zwischen den Matches, gemeinsames Abendessen im Anschluss. Alle Levels willkommen.',
    '[]'::jsonb,
    '[{"t":"16:30","l":"Check-in & Aufwärmen"},{"t":"17:00","l":"Turnierrunden"},{"t":"20:00","l":"Apéro & Dinner"},{"t":"23:30","l":"Ausklang"}]'::jsonb),
  ('ev-jun26-bs-lunch', '10. SportNexus-Lunch Basel', 'Alessandra Keller & Stefan Pfister', '2026-06-02', '11:30 – 14:00', 'Basel', 'Atlantis Basel', 'Klosterberg 13, 4051 Basel', 47, 'upcoming', false,
    'Lunch-Talk mit Alessandra Keller und Stefan Pfister im Atlantis Basel.',
    'https://events.guestoo.de/proxy/api/asset/3d4e4a52-d2f0-4a93-8cbb-854018d4c4fd.jpg?x=1770121924314',
    'Die zehnte Ausgabe des SportNexus-Lunches — dieses Mal in Basel. Alessandra Keller und Stefan Pfister im Doppel-Talk, anschliessend Lunch und Networking im Atlantis.',
    '[{"name":"Alessandra Keller","role":"Gast"},{"name":"Stefan Pfister","role":"Gast"}]'::jsonb,
    '[{"t":"11:30","l":"Empfang"},{"t":"12:15","l":"Talk"},{"t":"13:00","l":"Lunch"},{"t":"14:00","l":"Abschluss"}]'::jsonb),
  ('ev-sep26-golf', 'SportNexus Golfevent', '2er Scramble & Einführung für Nicht-Golfer', '2026-09-24', '16:30 – 22:00', 'Frick', 'Golf Fricktal', 'Frick', 42, 'upcoming', false,
    'Plauschturnier und Golfeinführung — für Golfer und Nicht-Golfer. Nicht-Golfer starten erst um 18:30 Uhr.',
    'https://events.guestoo.de/proxy/api/asset/d54252f6-ae3f-41b8-aeda-986a5fd9cb69.png?x=1773603620108',
    'Offenes Format für alle Members: 2er-Scramble-Plauschturnier für Golfer ab 16:30 Uhr, parallel eine Golfeinführung für Nicht-Golfer ab 18:30 Uhr. Gemeinsamer Apéro und Abendessen im Clubhaus.',
    '[]'::jsonb,
    '[{"t":"16:30","l":"Start Turnier (Golfer)"},{"t":"18:30","l":"Start Einführung (Nicht-Golfer)"},{"t":"20:00","l":"Apéro & Dinner"},{"t":"22:00","l":"Abschluss"}]'::jsonb),
  ('ev-mar26-zh', 'SportNexus Lunch Zürich', 'Andy Schmid & Pascal Jenny', '2026-03-03', '11:30 – 14:00', 'Zürich', 'Restaurant Metropol', 'Fraumünsterstrasse 12, 8001 Zürich', 70, 'past', false,
    'Pokal, National-Trainer und 70 Teilnehmende. Die zwei Aushängeschilder des Schweizer Handballs im Talk.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/69b148832365b2d645660b2a_SportNexus-Ma%CC%88rz26-KMEDIA-DSC02089-A.jpg',
    'Eine leistungsorientierte Wohlfühloase, grosse Ziele und ein Team auf dem Weg zur Weltspitze. 70 Teilnehmende, Pokal auf dem Tisch.',
    '[{"name":"Andy Schmid","role":"Handball-Legende"},{"name":"Pascal Jenny","role":"Nationaltrainer"}]'::jsonb,
    '[]'::jsonb),
  ('ev-jan26-zh', 'SportNexus Lunch Zürich', 'Daniel & Jonas Kalt', '2026-01-22', '11:30 – 14:00', 'Zürich', 'Baur au Lac', 'Talstrasse 1, 8001 Zürich', 68, 'past', false,
    'Vater und Sohn über Wahrscheinlichkeiten — im Sport und an den Finanzmärkten.',
    'https://cdn.prod.website-files.com/68d390b6028a7796367f36b3/699dae3f5dc68642ba59b47b_BF105291.jpg',
    'Daniel und Sohn Jonas über Wahrscheinlichkeiten — im Sport und an den Finanzmärkten. Ein Dialog zwischen zwei Generationen und zwei Welten, die näher beieinander liegen als man denkt.',
    '[{"name":"Daniel Kalt","role":"UBS Chief Economist"},{"name":"Jonas Kalt","role":"Profi-Sportler"}]'::jsonb,
    '[]'::jsonb);
